Output demo.gif

Set TypingSpeed 150ms
Set Width 2000
Set Height 1200
Set FontSize 20

Require tresor

Type "tresor mypasswor"
Tab
Sleep 500ms
Enter
Sleep 500ms
Type "foo"
Sleep 500ms
Enter

Sleep 2s
Type "j"
Sleep 1s

Type "l"
Sleep 1s
Type@750ms "jjj"
Sleep 1.5s
Type "y"
Sleep 1.5s
Type "h"

Sleep 1s
Type "j"
Sleep 1s

Type "l"
Sleep 3s
Type "h"

Sleep 1s

Type@500ms "jj"
Sleep 1.5s
Type ":q"
Sleep 1s
Enter
Sleep 1s
Ctrl+D

