name: Go test

on:
  push:
    branches:
      - "master"
      - "ci"
  pull_request:
    branches:
      - "master"

jobs:
  go-test:
    name: Go test
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Check formatting
        run: test -z $(gofmt -l .)

      - name: Run tests
        run: go test ./...

